name: 🐛 Bug Report
description: Create a report to help us reproduce and fix the bug

body:
- type: markdown
  attributes:
    value: >
      #### Before submitting a bug, please make sure the issue hasn't been already addressed by searching through [the existing and past issues](https://github.com/qqaatw/JciHitachiHA/issues?q=is%3Aissue+sort%3Acreated-desc+).
- type: textarea
  attributes:
    label: 🐛 Describe the bug
    description: |
      Please provide a clear and concise description of what the bug is.

      Please also paste or describe the results you observe instead of the expected results. If you observe an error or anomaly, please paste the error message including the **full** traceback of the exception. It may be relevant to wrap error messages in ```` ```triple quotes blocks``` ````.
    placeholder: |
      A clear and concise description of what the bug is.

      ```
      The error message you got, with the full traceback.
      ```
  validations:
    required: true
- type: textarea
  attributes:
    label: Environment Information
    description: |
      Please provide your environment information for debugging purposes.

      It should include HA version, JciHitachiHA version, device models.
  validations:
    required: true
- type: markdown
  attributes:
    value: >
      Thanks for contributing 🎉!